ruleDirs:
  - rules/typescript
  - rules/javascript
  - rules/java
  - rules/python
  - rules/kotlin
  - rules/go
  - rules/lua
  - rules/bash
  - rules/html
  - rules/css
  - rules/yaml
  - rules/markdown
  - rules/c
  - rules/cpp
  - rules/csharp
  - rules/rust
  - rules/haskell
  - rules/json
